#include "launcher_theme.hxx"

namespace sf4e {
namespace launcher {

QString LauncherStylesheet() {
	return QStringLiteral(
		"QMainWindow, QWidget { background: #050606; color: #d6d9dc; font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; }"
		"QLabel#eyebrow { color: #929aa2; font-size: 11px; font-weight: 600; letter-spacing: 1px; }"
		"QLabel#title { color: #f5f7f8; font-size: 25px; font-weight: 700; }"
		"QLabel#subtitle { color: #a9afb5; }"
		"QLabel#versionBadge { background: #0c0f10; color: #aeb5bb; border: 1px solid #22272a; padding: 6px 12px; border-radius: 3px; }"
		"QLabel#warningBanner { background: #121006; color: #d8c27a; border: 1px solid #302811; padding: 10px; border-radius: 3px; }"
		"QLabel#hint { color: #7c838a; font-size: 12px; }"
		"QLabel#connectionLine { color: #d7dce0; font-weight: 700; }"
		"QLabel#toastLabel { background: #101214; border: 1px solid #2a3034; padding: 8px 12px; border-radius: 2px; }"
		"QLabel#toastLabel[toastKind=\"error\"] { color: #f0a0a0; border-color: #5a3030; }"
		"QLabel#toastLabel[toastKind=\"success\"] { color: #a8d4a0; border-color: #305a30; }"
		"QLabel#scopeHeading { color: #c6cbd0; font-weight: 700; font-size: 12px; }"
		"QLabel#scopeText { color: #8a9198; font-size: 12px; }"
		"QLabel#modeCardTitle { color: #f0f2f4; font-weight: 700; font-size: 15px; }"
		"QLabel#modeCardDesc { color: #8a9198; font-size: 12px; }"
		"QLabel#shareCardTitle { color: #929aa2; font-size: 11px; font-weight: 600; text-transform: uppercase; }"
		"QLabel#shareCardValue { color: #f5f7f8; font-size: 18px; font-weight: 700; letter-spacing: 1px; }"
		"QLabel#updateStatus { color: #8a9198; font-size: 12px; }"
		"QLabel#updateStatus[updateKind=\"success\"] { color: #a8d4a0; }"
		"QLabel#updateStatus[updateKind=\"error\"] { color: #f0a0a0; }"
		"QGroupBox { background: #0c0e10; border: 1px solid #3d464f; border-radius: 3px; margin-top: 12px; padding: 12px 8px 8px 8px; font-weight: 700; }"
		"QGroupBox::title { subcontrol-origin: margin; left: 8px; padding: 0 4px; color: #c6cbd0; background: #050606; }"
		"QLineEdit, QSpinBox, QPlainTextEdit, QComboBox { background: #070808; color: #d6d9dc; border: 1px solid #3d464f; border-radius: 2px; padding: 6px; }"
		"QLineEdit:focus, QSpinBox:focus, QPlainTextEdit:focus, QComboBox:focus { border: 1px solid #d14a4a; }"
		"QLineEdit#roomCodeInput { font-size: 20px; font-weight: 700; letter-spacing: 2px; padding: 10px; }"
		"QPushButton#primaryButton { background: #8e2f32; color: #fff3f3; border: 1px solid #a33a3d; padding: 10px 16px; font-weight: 700; border-radius: 2px; }"
		"QPushButton#primaryButton:hover { background: #a33a3d; }"
		"QPushButton#primaryButton:disabled { background: #3a2021; color: #8a7a7a; border-color: #2a2020; }"
		"QPushButton#secondaryButton { background: #101214; color: #d6d9dc; border: 1px solid #3d464f; padding: 8px 12px; border-radius: 2px; }"
		"QPushButton#secondaryButton:hover { border-color: #d14a4a; background: #14181b; }"
		"QPushButton#secondaryButton:disabled { color: #666; border-color: #2a3034; }"
		"QPushButton#stepperButton { background: #101214; color: #d6d9dc; border: 1px solid #3d464f; min-height: 28px; border-radius: 2px; }"
		"QPushButton#modeCardHost, QPushButton#modeCardJoin, QPushButton#modeCardOffline {"
		"  background: #0e1012; border: 1px solid #4a545e; border-left-width: 3px; text-align: left;"
		"  border-radius: 3px; min-height: 72px; padding: 4px 2px; }"
		"QPushButton#modeCardHost { border-left-color: #d14a4a; }"
		"QPushButton#modeCardJoin { border-left-color: #5ecf8f; }"
		"QPushButton#modeCardOffline { border-left-color: #8a9198; }"
		"QPushButton#modeCardHost:hover, QPushButton#modeCardJoin:hover, QPushButton#modeCardOffline:hover {"
		"  background: #14181b; border-color: #6a7580; border-left-width: 3px; }"
		"QPushButton#modeCardHost:hover { border-left-color: #e85c5c; }"
		"QPushButton#modeCardJoin:hover { border-left-color: #7ae0a8; }"
		"QPushButton#modeCardOffline:hover { border-left-color: #b0b7be; }"
		"QPushButton#modeCardHost:pressed, QPushButton#modeCardJoin:pressed, QPushButton#modeCardOffline:pressed {"
		"  background: #181c20; border-color: #d14a4a; }"
		"QPushButton#segmentBtn { background: #0a0b0c; color: #9aa1a7; border: 1px solid #3d464f; padding: 8px 14px; border-radius: 2px; }"
		"QPushButton#segmentBtn:checked { background: #14181b; color: #f0f2f4; border: 1px solid #5a636d; border-bottom: 2px solid #d14a4a; }"
		"QPushButton#segmentBtn:hover { border-color: #5a636d; }"
		"QPushButton#backButton { background: transparent; color: #9aa1a7; border: none; padding: 4px 0; text-align: left; font-weight: 600; }"
		"QPushButton#backButton:hover { color: #d14a4a; }"
		"QWidget#shareCard { background: #0c0e10; border: 1px solid #3d464f; border-radius: 3px; }"
		"QWidget#shareCard[shareEmpty=\"true\"] { border-color: #2f363d; }"
		"QWidget#shareCard[shareEmpty=\"true\"] QLabel#shareCardValue { color: #555; }"
		"QListWidget { background: #070808; border: 1px solid #3d464f; border-radius: 3px; }"
		"QListWidget::item { padding: 10px; border-bottom: 1px solid #2f363d; }"
		"QListWidget::item:selected { background: #121416; color: #f0f2f4; }"
		"QScrollArea { border: none; background: transparent; }"
		"QWidget.advancedOnly { }"
	);
}

} // namespace launcher
} // namespace sf4e
